name: Build and push Kubero image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCR_TOKEN }}
          password: ${{ secrets.DOCR_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: |
            registry.digitalocean.com/pinpoint-internal-platform-staging/kubero:v3.1.1-patched
            registry.digitalocean.com/pinpoint-internal-platform-staging/kubero:latest
